services:
  # ----------------------
  # MongoDB
  # ----------------------
  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: gdash
    networks:
      - appnet

  # ----------------------
  # RabbitMQ
  # ----------------------
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - appnet

  # ----------------------
  # Producer (Python)
  # ----------------------
  producer:
    build: ./Python
    restart: always
    depends_on:
      rabbitmq:
        condition: service_started
    env_file:
      - ./Python/.env
    ports:
      - "8001:8001"
    networks:
      - appnet

  # ----------------------
  # Go Worker
  # ----------------------
  go_worker:
    build:
      context: ./go_worker
      dockerfile: Dockerfile
    restart: always
    depends_on:
      rabbitmq:
        condition: service_started
      nest_api:
        condition: service_started
    env_file:
      - ./go_worker/.env
    networks:
      - appnet

  # ----------------------
  # NestJS API (DEV)
  # ----------------------
  nest_api:
    build:
      context: ./Back-end/desafio-gdash
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./Back-end/desafio-gdash/.env
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - appnet

# ----------------------
# Network
# ----------------------
networks:
  appnet:
    driver: bridge
